[project]
name = "django-staticsite"
version = "0.1.0"
description = "Reference implementation of a staticsite contrib module for Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2",
]
